name: kidventure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_3d_controller: ^2.1.0
  flutter_screenutil: ^5.9.3
  youtube_player_flutter: ^9.1.1
  flutter_flip_card: ^0.0.6
  google_fonts: ^6.2.1
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/models/
  fonts:
    - family: CrimsonText
      fonts:
        - asset: assets/fonts/CrimsonText-Bold.ttf
        - asset: assets/fonts/CrimsonText-BoldItalic.ttf
        - asset: assets/fonts/CrimsonText-Italic.ttf
        - asset: assets/fonts/CrimsonText-Regular.ttf
        - asset: assets/fonts/CrimsonText-SemiBold.ttf
        - asset: assets/fonts/CrimsonText-SemiBoldItalic.ttf